In [1]:
import numpy as np

In [2]:
a = np.array([1,2])
b = np.array([3,4])
print(np.append(a,b,axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [3]:
# initial state as tensor
agentF = Unicycle2D(np.array([0,0.2,0]),dt,3,FoV,max_D,min_D)

agentF.X0 = torch.tensor(np.array([0,0.2,0]),dtype=torch.float, requires_grad=True)

#create layers

dynam = torch_dynamics.apply

state_tensors = [torch.tensor(agentF.X,dtype=torch.float,requires_grad=True)]
input_tensors = []

for i in range(N):  # horizon
    
    u = policy(agentF,agentT)  # tensor
    
    x = state_tensors[-1]
    
    x_ = dynam(x,u)
    
    
    # compute reward: should be a reward
    r = compute_reward(x_)
    
    # Store state and input tensors
    state_tensors.append(x_)
    input_tensors.append(u)
    
    # visualize
    robotF.step(u.detach().numpy())    
    
    



# form MDP

NameError: name 'Unicycle2D' is not defined

In [4]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
import torch
a = torch.tensor([ [0],[0] ])
b = torch.tensor([ [2],[3] ] )
print(a-b)

tensor([[-2],
        [-3]])


In [6]:
a = torch.tensor([[0]])
b = torch.tensor(3)
print(a+b)

tensor([[3]])


In [7]:
a + 1

tensor([[1]])

In [8]:
x1 = torch.ones(1, requires_grad=True)
x2 = torch.tensor(2, requires_grad=True, dtype=torch.float)

In [9]:
y = x1 + x2
z = x1 - x2

In [10]:
y.backward(retain_graph=True)

In [11]:
print(x2.grad)

tensor(1.)


In [12]:
print(x1.grad)

tensor([1.])


In [13]:
print(x1.grad)

tensor([1.])


In [14]:
x2 = torch.tensor(2, requires_grad=True, dtype=torch.float)
y = x2
y.backward()

In [15]:
print(x2.grad)

tensor(1.)


In [16]:
a = [[1],[2],[3],[4],[5]]
a[-2:]

[[4], [5]]

In [17]:
x1

tensor([1.], requires_grad=True)

In [18]:
x2

tensor(2., requires_grad=True)

In [19]:
x1 = torch.ones(1, requires_grad=True)
y = x1**2
y.retain_grad()
z = (y**3)
z.retain_grad()
print(z)

tensor([1.], grad_fn=<PowBackward0>)


In [20]:
z.backward()

In [21]:
y.grad

tensor([3.])

In [22]:
x1.grad

tensor([6.])

In [23]:
y.grad

tensor([3.])

In [24]:
x1 = torch.ones(1, requires_grad=True)
y = torch.cos(x1)
y.retain_grad()
z = y + 2*x1
# z.retain_grad()
z.backward()
print(z)

tensor([2.5403], grad_fn=<AddBackward0>)


In [25]:
print(y.grad)

tensor([1.])


In [26]:
x1.grad

tensor([1.1585])

In [27]:
2 - np.sin(1)

1.1585290151921035

In [28]:
def square(x):
    y = torch.sin(x)
    print("yy",y)
    return y#torch.square(torch.sin(x))

In [29]:
x1 = torch.ones(1, requires_grad=True)
# y = torch.cat((x1,x1),0)

y = square(torch.sin(x1))
# print(y)
# y.retain_grad()
# z = y + 2*x1
z = y.sum()
print(z)
z.backward()
# y.backward()

yy tensor([0.7456], grad_fn=<SinBackward>)
tensor(0.7456, grad_fn=<SumBackward0>)


In [30]:
x1.grad

tensor([0.3600])

In [31]:
x1 = torch.ones(1, requires_grad=True)
y = x1 + 0
y.retain_grad()
z = y + 2*x1
print(z)
z.backward()
# y.backward()

tensor([3.], grad_fn=<AddBackward0>)


In [32]:
y.grad

tensor([1.])

In [33]:
x1.grad

tensor([3.])

In [84]:
x1 = 2*torch.ones((1,1), requires_grad=True)
x1.retain_grad()
x1sum = 0
gsum = 0

g = torch.cos(x1[0,0])
g.retain_grad()
g.backward(retain_graph=True)
print("g")
print(x1.grad)
print(x1.grad)
x1sum += x1.grad

# print("1: g: ",g.grad)
# gsum += g.grad

h = torch.square(g)
h.retain_grad()
# h.backward(retain_graph=True)
# print("h")
# print(x1.grad) #-0.1525, 0.7568
# print(x1.grad - x1sum)
# x1sum += x1.grad - x1sum
# gsum += g.grad - gsum


i = torch.cos(h)
i.backward(retain_graph=True)
print("i")
# print(x1.grad) #-0.2829, 0.7789    ## -0.1304 independently
# print(x1.grad - x1sum)
x1sum += x1.grad - x1sum

print("gsum",gsum)
print("grad org",g.grad)
print("g grad",g.grad - gsum)  #0.1434
gsum = g.grad - gsum

print(x1,g,h,i)

g
tensor([[-0.9093]])
tensor([[-0.9093]])
i
gsum 0
grad org tensor(1.1434)
g grad tensor(1.1434)
tensor([[2.]], grad_fn=<MulBackward0>) tensor(-0.4161, grad_fn=<CosBackward>) tensor(0.1732, grad_fn=<PowBackward0>) tensor(0.9850, grad_fn=<CosBackward>)


In [130]:
x1 = torch.tensor([2.0],requires_grad=True)
theta = torch.tensor([10.0],requires_grad=True)
dt = 1.5

# 1
u1 = x1 + theta
x2 = x1 + u1*dt
u1.retain_grad()
x2.retain_grad()

print("1: ",x1,theta,u1,x2)

# 2

theta1 = theta + torch.tensor([0])
theta1.retain_grad()
print(theta1)

u2 = x2 + theta1
x3 = x2 + u2*dt
u2.retain_grad()
x3.retain_grad()

print("2: ",x2,theta1,u2,x3)

# grads
xx = x3.sum()
xx.backward()
print(u2.grad, theta.grad, theta1.grad, x1.grad)

1:  tensor([2.], requires_grad=True) tensor([10.], requires_grad=True) tensor([12.], grad_fn=<AddBackward0>) tensor([20.], grad_fn=<AddBackward0>)
tensor([10.], grad_fn=<AddBackward0>)
2:  tensor([20.], grad_fn=<AddBackward0>) tensor([10.], grad_fn=<AddBackward0>) tensor([30.], grad_fn=<AddBackward0>) tensor([65.], grad_fn=<AddBackward0>)
tensor([1.5000]) tensor([5.2500]) tensor([1.5000]) tensor([6.2500])


In [134]:
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer

# Controller here
u = cp.Variable(1)
x = cp.Parameter(1)
th = cp.Parameter(1)
delta = u - x - th
objective = cp.Minimize(cp.square(delta))
problem = cp.Problem(objective)
cvxpylayer = CvxpyLayer(problem, parameters=[x, th], variables=[u])


x1 = torch.tensor([2.0],requires_grad=True)
theta = torch.tensor([10.0],requires_grad=True)
dt = 1.5

# 1
u1, = cvxpylayer(x1, theta)  #x1 + theta

assert problem.is_dpp()
x2 = x1 + u1*dt
u1.retain_grad()
x2.retain_grad()

print(x1,theta,u1,x2)

# 2

theta1 = theta + torch.tensor([0])
theta1.retain_grad()
print(theta1)

u2, = cvxpylayer(x2, theta1)  #x2 + theta1
x3 = x2 + u2*dt
u2.retain_grad()
x3.retain_grad()

print(x2,theta1,u2,x3)

# grads
xx = x3.sum()
xx.backward()
print(u2.grad, theta.grad, theta1.grad, x1.grad)

tensor([2.], requires_grad=True) tensor([10.], requires_grad=True) tensor([12.], grad_fn=<_CvxpyLayerFnFnBackward>) tensor([20.], grad_fn=<AddBackward0>)
tensor([10.], grad_fn=<AddBackward0>)
tensor([20.], grad_fn=<AddBackward0>) tensor([10.], grad_fn=<AddBackward0>) tensor([30.], grad_fn=<_CvxpyLayerFnFnBackward>) tensor([65.], grad_fn=<AddBackward0>)
tensor([1.5000]) tensor([5.2500]) tensor([1.5000]) tensor([6.2500])
