In [2]:
import numpy as np

In [2]:
a = np.array([1,2])
b = np.array([3,4])
print(np.append(a,b,axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [3]:
# initial state as tensor
agentF = Unicycle2D(np.array([0,0.2,0]),dt,3,FoV,max_D,min_D)

agentF.X0 = torch.tensor(np.array([0,0.2,0]),dtype=torch.float, requires_grad=True)

#create layers

dynam = torch_dynamics.apply

state_tensors = [torch.tensor(agentF.X,dtype=torch.float,requires_grad=True)]
input_tensors = []

for i in range(N):  # horizon
    
    u = policy(agentF,agentT)  # tensor
    
    x = state_tensors[-1]
    
    x_ = dynam(x,u)
    
    
    # compute reward: should be a reward
    r = compute_reward(x_)
    
    # Store state and input tensors
    state_tensors.append(x_)
    input_tensors.append(u)
    
    # visualize
    robotF.step(u.detach().numpy())    
    
    



# form MDP

NameError: name 'Unicycle2D' is not defined

In [4]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import torch
a = torch.tensor([ [0],[0] ])
b = torch.tensor([ [2],[3] ] )
print(a-b)

tensor([[-2],
        [-3]])


In [21]:
a = torch.tensor([[0]])
b = torch.tensor(3)
print(a+b)

tensor([[3]])


In [22]:
a + 1

tensor([[1]])

In [58]:
x1 = torch.ones(1, requires_grad=True)
x2 = torch.tensor(2, requires_grad=True, dtype=torch.float)

In [59]:
y = x1 + x2
z = x1 - x2

In [60]:
y.backward(retain_graph=True)

In [64]:
print(x2.grad)

tensor(1.)


In [62]:
print(x1.grad)

tensor([1.])


In [63]:
print(x1.grad)

tensor([1.])


In [56]:
x2 = torch.tensor(2, requires_grad=True, dtype=torch.float)
y = x2
y.backward()

In [45]:
print(x2.grad)

tensor(1.)


In [71]:
a = [[1],[2],[3],[4],[5]]
a[-2:]

[[4], [5]]

In [72]:
x1

tensor([1.], requires_grad=True)

In [73]:
x2

tensor(2., requires_grad=True)

In [93]:
x1 = torch.ones(1, requires_grad=True)
y = x1**2
y.retain_grad()
z = (y**3)
z.retain_grad()
print(z)

tensor([1.], grad_fn=<PowBackward0>)


In [94]:
z.backward()

In [95]:
y.grad

tensor([3.])

In [96]:
x1.grad

tensor([6.])

In [97]:
y.grad

tensor([3.])

In [120]:
x1 = torch.ones(1, requires_grad=True)
y = torch.cos(x1)
y.retain_grad()
z = y + 2*x1
# z.retain_grad()
z.backward()
print(z)

tensor([2.5403], grad_fn=<AddBackward0>)


In [121]:
print(y.grad)

tensor([1.])


In [122]:
x1.grad

tensor([1.1585])

In [126]:
2 - np.sin(1)

1.1585290151921035

In [26]:
def square(x):
    y = torch.sin(x)
    print("yy",y)
    return y#torch.square(torch.sin(x))

In [29]:
x1 = torch.ones(1, requires_grad=True)
# y = torch.cat((x1,x1),0)

y = square(torch.sin(x1))
# print(y)
# y.retain_grad()
# z = y + 2*x1
z = y.sum()
print(z)
z.backward()
# y.backward()

yy tensor([0.7456], grad_fn=<SinBackward>)
tensor(0.7456, grad_fn=<SumBackward0>)


In [175]:
x1.grad

tensor([2.])

In [182]:
x1 = torch.ones(1, requires_grad=True)
y = x1 + 0
y.retain_grad()
z = y + 2*x1
print(z)
z.backward()
# y.backward()

tensor([3.], grad_fn=<AddBackward0>)


In [183]:
y.grad

tensor([1.])

In [184]:
x1.grad

tensor([3.])

In [14]:
x1 = 2*torch.ones((1,1), requires_grad=True)
x1.retain_grad()
g = torch.cos(x1[0,0])
g.backward()
print(x1.grad)
print(x1,g)

tensor([[-0.9093]])
tensor([[2.]], grad_fn=<MulBackward0>) tensor(-0.4161, grad_fn=<CosBackward>)
